version: '3.8'
services:
  registration-service:
    build: .
    image: registration-service
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/registrationServiceDb
      - SPRING_DATASOURCE_USERNAME=Faruh
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://51.250.40.135:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true

  db:
    image: postgres:15.0-alpine
    ports:
      - "6531:5432"
    environment:
      - POSTGRES_DB=registrationServiceDb
      - POSTGRES_USER=Faruh
      - POSTGRES_PASSWORD=iamroot
