version: '3.8'
services:
  registration-service:
    build: .
    image: registration-service
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL:${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME:${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD:${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EVENT_SERVICE_NAME:{EVENT_SERVICE_NAME}
      - USER_SERVICE_NAME:{USER_SERVICE_NAME}

  db:
    image: postgres:15.0-alpine
    ports:
      - "6531:5432"
    environment:
      - POSTGRES_DB=registrationServiceDb
      - POSTGRES_USER=Faruh
      - POSTGRES_PASSWORD=iamroot
