DROP TABLE IF EXISTS registrations;


CREATE TABLE IF NOT EXISTS registrations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255)  NOT NULL,
    email             VARCHAR(255)  NOT NULL,
    phone             VARCHAR(255)  NOT NULL,
    event_id          BIGINT        NOT NULL,
    number            INT           NOT NULL,
    password          VARCHAR(1024) NOT NULL,
    created_date_time TIMESTAMP     NOT NULL,
    status            VARCHAR(255)  NOT NULL,
    rejected_reason   VARCHAR(255)
);